# Generated by Django 6.1.2 on 2026-10-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_sw', models.CharField(blank=True, max_length=150)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'lookup categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_sw', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('country_code', models.CharField(default='TZ', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_sw', models.CharField(blank=True, max_length=150)),
                ('code', models.SlugField(max_length=60)),
                ('description_en', models.TextField(blank=True)),
                ('description_sw', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='lookups.lookupcategory')),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_sw', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='lookups.region')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_sw', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='lookups.district')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_sw', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('locality_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='lookups.lookupvalue')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='lookups.ward')),
            ],
            options={
                'verbose_name_plural': 'localities (villages/streets)',
                'ordering': ['name_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='lookupvalue',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='unique_lookup_category_code'),
        ),
    ]
