# Generated by Django 6.1.2 on 2026-10-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('users', '0003_agentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='coverage_districts',
            field=models.ManyToManyField(blank=True, related_name='covering_agents', to='lookups.district'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='coverage_localities',
            field=models.ManyToManyField(blank=True, related_name='covering_agents', to='lookups.locality'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='coverage_regions',
            field=models.ManyToManyField(blank=True, related_name='covering_agents', to='lookups.region'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='coverage_wards',
            field=models.ManyToManyField(blank=True, related_name='covering_agents', to='lookups.ward'),
        ),
    ]
