# Generated by Django 6.1.2 on 2026-10-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconversation',
            name='consecutive_off_topic_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
