# Generated by Django 6.1.2 on 2026-10-07 21:16

import django.core.validators
import django.db.models.deletion
import houses.models
from django.conf import settings
from django.db import migrations, models


def assign_existing_houses_to_seed_agent(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Role = apps.get_model('users', 'Role')
    AgentProfile = apps.get_model('users', 'AgentProfile')
    House = apps.get_model('houses', 'House')

    role, _ = Role.objects.get_or_create(name='Agent', defaults={'description': 'Can publish and manage property listings'})
    agent, created = User.objects.get_or_create(
        username='sample_agent',
        defaults={'email': 'agent@sweethomez.local', 'first_name': 'SweetHomez', 'last_name': 'Agent'},
    )
    if created:
        agent.password = '!'
        agent.save(update_fields=['password'])
    agent.roles.add(role)
    AgentProfile.objects.get_or_create(user=agent, defaults={'agency_name': 'SweetHomez Realty', 'phone_number': '+255 700 000 000', 'is_verified': True})

    for house in House.objects.all():
        house.agent = agent
        house.price_period = 'monthly' if house.listing_type == 'rent' else 'one_time'
        if not house.region:
            house.region = house.address.split(',')[-1].strip() if ',' in house.address else 'Tanzania'
        house.save(update_fields=['agent', 'price_period', 'region'])


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0003_agentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(blank=True, upload_to=houses.models.house_media_upload_path)),
                ('external_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'house media',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NearbyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('atm', 'ATM'), ('police', 'Police station'), ('gym', 'Gym'), ('fuel_station', 'Fuel station'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital or clinic'), ('school', 'School'), ('market', 'Market or supermarket'), ('public_transport', 'Public transport'), ('restaurant', 'Restaurant'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['distance_km', 'facility_type'],
            },
        ),
        migrations.RenameField(
            model_name='house',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='rooms',
            new_name='bedrooms',
        ),
        migrations.AddField(
            model_name='house',
            name='advance_payment_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='house_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='agent_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='agent_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='agent_fee_type',
            field=models.CharField(choices=[('none', 'No agent fee'), ('fixed', 'Fixed amount'), ('percentage', 'Percentage of price')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='country',
            field=models.CharField(default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='ensuite_bedrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchens',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='price_period',
            field=models.CharField(choices=[('one_time', 'One-time sale price'), ('daily', 'Per day'), ('weekly', 'Per week'), ('monthly', 'Per month'), ('quarterly', 'Per three months'), ('semiannual', 'Per six months'), ('annual', 'Per year')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='region',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='security_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='water_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(assign_existing_houses_to_seed_agent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['listing_type', 'is_available'], name='houses_hous_listing_f42b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['region', 'district'], name='houses_hous_region_08e616_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['bedrooms'], name='houses_hous_bedroom_236fee_idx'),
        ),
        migrations.AddField(
            model_name='housemedia',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='houses.house'),
        ),
        migrations.AddField(
            model_name='nearbyfacility',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_facilities', to='houses.house'),
        ),
    ]
