# Generated by Django 6.1.2 on 2026-10-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_housemedia_nearbyfacility_remove_house_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
