# Generated by Django 6.1.2 on 2026-10-07 21:22

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_content_to_english(apps, schema_editor):
    House = apps.get_model('houses', 'House')
    HouseTranslation = apps.get_model('houses', 'HouseTranslation')
    HouseTranslation.objects.bulk_create([
        HouseTranslation(
            house_id=house.id,
            language_code='en',
            title=house.title,
            description=house.description,
            address=house.address,
        )
        for house in House.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_bedrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='houses.house')),
            ],
            options={
                'ordering': ['language_code'],
                'constraints': [models.UniqueConstraint(fields=('house', 'language_code'), name='unique_house_language')],
            },
        ),
        migrations.RunPython(copy_existing_content_to_english, migrations.RunPython.noop),
    ]
