# Generated by Django 6.1.2 on 2026-10-09 08:08

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def connect_existing_house_locations(apps, schema_editor):
    House = apps.get_model("houses", "House")
    Ward = apps.get_model("lookups", "Ward")
    for house in House.objects.all():
        ward = Ward.objects.filter(name_en__iexact=house.ward).select_related("district__region").first()
        if ward is None:
            ward = Ward.objects.filter(
                name_en__iexact=house.address,
                district__name_en__iexact=house.district,
            ).select_related("district__region").first()
        if ward:
            house.ward_record_id = ward.pk
            house.district_record_id = ward.district_id
            house.region_record_id = ward.district.region_id
            street = ward.localities.filter(locality_type__code="street").first()
            house.street_id = street.pk if street else None
        if house.is_available:
            house.availability_last_confirmed_at = timezone.now()
        house.save(update_fields=[
            "ward_record", "district_record", "region_record", "street",
            "availability_last_confirmed_at",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_housetranslation'),
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='availability_last_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='district_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='lookups.district'),
        ),
        migrations.AddField(
            model_name='house',
            name='region_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='lookups.region'),
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='lookups.locality'),
        ),
        migrations.AddField(
            model_name='house',
            name='ward_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='lookups.ward'),
        ),
        migrations.RunPython(connect_existing_house_locations, migrations.RunPython.noop),
    ]
